< !doctype html >
    <
    html lang = "en" >
    <
    head >
    <
    meta charset = "UTF-8" / >
    <
    link
rel = "icon"
type = "image/svg+xml"
href = "/assets/zijus_icon_v2-mgHfrhkP.png" /
    >
    <
    link rel = "preconnect"
href = "https://fonts.googleapis.com" / >
    <
    link rel = "preconnect"
href = "https://fonts.gstatic.com"
crossorigin / >
    <
    link
href = "https://fonts.googleapis.com/css2?family=Assistant:wght@200..800&display=swap"
rel = "stylesheet" /
    >

    <
    meta name = "viewport"
content = "width=device-width, initial-scale=1.0" / >
    <
    title > Zijus - Home < /title> <
    script type = "module"
crossorigin src = "/assets/index-CynXZRqW.js" > < /script> <
    link rel = "stylesheet"
crossorigin href = "/assets/index-CulE56w1.css" >
    <
    /head>

    <
    body
class = "assistant_d6140c7-module__oTyDba__variable bg-gray-50 font-inter tracking-tight text-gray-900 antialiased" >
    <
    div id = "root" > < /div> <
    script src = "/env.js" > < /script> <
    script
async
src = "https://www.googletagmanager.com/gtag/js?id=G-944ZZ8XF7D" >
    < /script> <
    script >
    window.dataLayer = window.dataLayer || [];

function gtag() {
    dataLayer.push(arguments);
}
gtag("js", new Date());
gtag("config", "G-944ZZ8XF7D"); <
/script>
<!-- <script async src="http://localhost:4000/zijus-webclient-jupiter-v0.2.js"
zijus - config = 'eyJ0aXRsZVRleHQiOiJaaWp1cyBBSSIsInN1YnRpdGxlVGV4dCI6IkhvdyBtYXkgSSBoZWxwIHlvdT8iLCJkZWZhdWx0Qm90TWVzc2FnZSI6eyJjb250ZW50IjoiSGkgdGhlcmUhIEknbSBhbiBBSSBhc3Npc3RhbnQgLSBhc2sgbWUgYW55dGhpbmcsIGFuZCBJJ2xsIGRvIG15IGJlc3QgdG8gaGVscCB5b3Ugb3V0ISJ9LCJoaW50VGV4dCI6IkFzayBtZSIsInRoZW1lIjp7Imljb25CZyI6ImJnLXN0b25lLTUwIiwiaGVhZGVyVGV4dENvbG9yIjoidGV4dC1zdG9uZS01MCIsImhlYWRlckdyYWRpZW50RGlyZWN0aW9uIjoiYmctZ3JhZGllbnQtdG8tciIsImhlYWRlckdyYWRpZW50RnJvbUNvbG9yIjoiZnJvbS1vcmFuZ2UtNjAwIiwiaGVhZGVyR3JhZGllbnRUb0NvbG9yIjoidG8tcHVycGxlLTYwMCIsImF2YXRhclNpemUiOiJ3LTEwIGgtMTAiLCJjaGF0QmFja2dyb3VuZCI6ImJnLXN0b25lLTUwIiwiYnViYmxlVXNlckJhY2tncm91bmQiOiJiZy1ibHVlLTUwMCIsImJ1YmJsZVVzZXJUZXh0Q29sb3IiOiJ0ZXh0LXN0b25lLTUwIiwiYnViYmxlQm90QmFja2dyb3VuZCI6ImJnLWdyYXktMjAwIiwiYnViYmxlQm90VGV4dENvbG9yIjoidGV4dC1ncmF5LTgwMCIsImJ1YmJsZVJhZGl1cyI6InJvdW5kZWQtMnhsIiwiYnViYmxlUGFkZGluZ1giOiJweC00IiwiYnViYmxlUGFkZGluZ1kiOiJweS0yIiwiaGVhZGVyR3JhZGllbnQiOiJiZy1ncmFkaWVudC10by1yIGZyb20tb3JhbmdlLTYwMCB0by1wdXJwbGUtNjAwIn0sImFsbG93RnVsbFNjcmVlbiI6ZmFsc2UsInNob3dBdHRhY2htZW50QnV0dG9uIjpmYWxzZSwic2hvd01pY0J1dHRvbiI6dHJ1ZSwic2hvd1NlYXJjaEJ1dHRvbiI6ZmFsc2UsInByaXZhY3lQb2xpY3lVcmwiOiJodHRwczovL3d3dy56aWp1cy5jb20vcHJpdmFjeS1wb2xpY3kiLCJ3ZWJzb2NrZXRVcmwiOiJodHRwczovL3ppanVzLTUzNTEtNDExOTUxNDM0NDYyLnVzLWNlbnRyYWwxLnJ1bi5hcHAvd3MiLCJjaGF0Ym90SWNvbiI6Imh0dHBzOi8vc3RvcmFnZS5nb29nbGVhcGlzLmNvbS96aWp1c3N0YXRpYy9pbWFnZXMvemlqdXMtNTM1MS1pY29uLnBuZyIsInRpdGxlSWNvbiI6Imh0dHBzOi8vc3RvcmFnZS5nb29nbGVhcGlzLmNvbS96aWp1c3N0YXRpYy9pbWFnZXMvemlqdXMtNTM1MS1pY29uLnBuZyIsInN1YnNjcmlwdGlvblR5cGUiOiJpZ25pdGUifQ==' > < /script> --> <
    script
async
src = "https://zijus-cdn.s3.eu-west-2.amazonaws.com/js/zijus-webclient-jupiter-v0.1.0.js"
zijus - config = "ewogICJ0aXRsZVRleHQiOiAiWmlqdXMgQUkiLAogICJzdWJ0aXRsZVRleHQiOiAiSG93IG1heSBJIGhlbHAgeW91PyIsCiAgImRlZmF1bHRCb3RNZXNzYWdlIjogewogICAgIkVOX1VTIjogewogICAgICAiY29udGVudCI6ICJIaSB0aGVyZSEgSSdtIGFuIEFJIGFzc2lzdGFudCAtIGFzayBtZSBhbnl0aGluZywgYW5kIEknbGwgZG8gbXkgYmVzdCB0byBoZWxwIHlvdSBvdXQhIiwKICAgICAgInNsb3RzIjogWwogICAgICAgIHsKICAgICAgICAgICJsYWJlbCI6ICJQcm9kdWN0IiwKICAgICAgICAgICJ2YWx1ZSI6ICJUZWxsIG1lIGFib3V0IHRoZSBwcm9kdWN0IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgImxhYmVsIjogIlByaWNpbmciLAogICAgICAgICAgInZhbHVlIjogIlRlbGwgbWUgYWJvdXQgdGhlIHByaWNpbmcgbW9kZWwiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibGFiZWwiOiAiTWVldGluZyIsCiAgICAgICAgICAidmFsdWUiOiAiSGVscCBtZSBzZXQgdXAgYSBtZWV0aW5nIgogICAgICAgIH0KICAgICAgXQogICAgfSwKICAgICJISV9JTiI6IHsKICAgICAgImNvbnRlbnQiOiAi4KSo4KSu4KS44KWN4KSk4KWHISDgpK7gpYjgpIIg4KSP4KSVIOCkj+CkhuCkiCDgpLjgpLngpL7gpK/gpJUg4KS54KWC4KSBIC0g4KSu4KWB4KSd4KS44KWHIOCkleClgeCkmyDgpK3gpYAg4KSq4KWC4KSb4KS/4KSPLCDgpJTgpLAg4KSu4KWI4KSCIOCkhuCkquCkleClgCDgpK7gpKbgpKYg4KSV4KSw4KSo4KWHIOCkleClgCDgpKrgpYLgpLDgpYAg4KSV4KWL4KS24KS/4KS2IOCkleCksOClguCkgeCkl+CkviEiLAogICAgICAic2xvdHMiOiBbCiAgICAgICAgewogICAgICAgICAgImxhYmVsIjogIuCkieCkpOCljeCkquCkvuCkpiIsCiAgICAgICAgICAidmFsdWUiOiAi4KSu4KWB4KSd4KWHIOCkieCkpOCljeCkquCkvuCkpiDgpJXgpYcg4KSs4KS+4KSw4KWHIOCkruClh+CkgiDgpKzgpKTgpL7gpIfgpI8iCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibGFiZWwiOiAi4KSu4KWC4KSy4KWN4KSvIOCkqOCkv+CksOCljeCkp+CkvuCksOCkoyIsCiAgICAgICAgICAidmFsdWUiOiAi4KSu4KWB4KSd4KWHIOCkruClguCksuCljeCkryDgpKjgpL/gpLDgpY3gpKfgpL7gpLDgpKMg4KSu4KWJ4KSh4KSyIOCkleClhyDgpKzgpL7gpLDgpYcg4KSu4KWH4KSCIOCkrOCkpOCkvuCkh+CkjyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJsYWJlbCI6ICLgpKzgpYjgpKDgpJUiLAogICAgICAgICAgInZhbHVlIjogIuCkruClh+CksOClgCDgpI/gpJUg4KSs4KWI4KSg4KSVIOCkqOCkv+CksOCljeCkp+CkvuCksOCkv+CkpCDgpJXgpLDgpKjgpYcg4KSu4KWH4KSCIOCkruCkpuCkpiDgpJXgpLDgpYfgpIIiCiAgICAgICAgfQogICAgICBdCiAgICB9LAogICAgIkZSX0NBIjogewogICAgICAiY29udGVudCI6ICJCb25qb3VyICEgSmUgc3VpcyB1biBhc3Npc3RhbnQgSUEgLSBwb3Nlei1tb2kgdm9zIHF1ZXN0aW9ucyBldCBqZSBmZXJhaSBkZSBtb24gbWlldXggcG91ciB2b3VzIGFpZGVyICEiLAogICAgICAic2xvdHMiOiBbCiAgICAgICAgewogICAgICAgICAgImxhYmVsIjogIlByb2R1aXQiLAogICAgICAgICAgInZhbHVlIjogIlBhcmxlei1tb2kgZHUgcHJvZHVpdCIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJsYWJlbCI6ICJUYXJpZmljYXRpb24iLAogICAgICAgICAgInZhbHVlIjogIlBhcmxlei1tb2kgZHUgbW9kw6hsZSBkZSB0YXJpZmljYXRpb24iCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibGFiZWwiOiAiUsOpdW5pb24iLAogICAgICAgICAgInZhbHVlIjogIkFpZGV6LW1vaSDDoCBvcmdhbmlzZXIgdW5lIHLDqXVuaW9uIgogICAgICAgIH0KICAgICAgXQogICAgfSwKICAgICJFU19FUyI6IHsKICAgICAgImNvbnRlbnQiOiAiwqFIb2xhISBTb3kgdW4gYXNpc3RlbnRlIGRlIElBIC0gcHJlZ8O6bnRhbWUgbG8gcXVlIHF1aWVyYXMgeSBoYXLDqSB0b2RvIGxvIHBvc2libGUgcGFyYSBheXVkYXJ0ZS4iLAogICAgICAic2xvdHMiOiBbCiAgICAgICAgewogICAgICAgICAgImxhYmVsIjogIlByb2R1Y3RvIiwKICAgICAgICAgICJ2YWx1ZSI6ICJDdcOpbnRhbWUgc29icmUgZWwgcHJvZHVjdG8iCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibGFiZWwiOiAiUHJlY2lvcyIsCiAgICAgICAgICAidmFsdWUiOiAiQ3XDqW50YW1lIHNvYnJlIGVsIG1vZGVsbyBkZSBwcmVjaW9zIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgImxhYmVsIjogIlJldW5pw7NuIiwKICAgICAgICAgICJ2YWx1ZSI6ICJBecO6ZGFtZSBhIG9yZ2FuaXphciB1bmEgcmV1bmnDs24iCiAgICAgICAgfQogICAgICBdCiAgICB9LAogICAgIkFSIjogewogICAgICAiY29udGVudCI6ICLZhdix2K3YqNin2YshINij2YbYpyDZhdiz2KfYudivINiw2YPZiiAtINin2LPYo9mE2YbZiiDYo9mKINi02YrYoSDZiNiz2KPYqNiw2YQg2YLYtdin2LHZiSDYrNmH2K/ZiiDZhNmF2LPYp9i52K/YqtmDISIsCiAgICAgICJzbG90cyI6IFsKICAgICAgICB7CiAgICAgICAgICAibGFiZWwiOiAi2KfZhNmF2YbYqtisIiwKICAgICAgICAgICJ2YWx1ZSI6ICLYo9iu2KjYsdmG2Yog2LnZhiDYp9mE2YXZhtiq2KwiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibGFiZWwiOiAi2KfZhNiq2LPYudmK2LEiLAogICAgICAgICAgInZhbHVlIjogItij2K7YqNix2YbZiiDYudmGINmG2YXZiNiw2Kwg2KfZhNiq2LPYudmK2LEiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAibGFiZWwiOiAi2KfZhNin2KzYqtmF2KfYuSIsCiAgICAgICAgICAidmFsdWUiOiAi2LPYp9i52K/ZhtmKINmB2Yog2KrZhti42YrZhSDYp9is2KrZhdin2LkiCiAgICAgICAgfQogICAgICBdCiAgICB9CiAgfSwKICAidGhlbWUiOiB7CiAgICAiaWNvbkJnIjogImJnLXNsYXRlLTk1MCIsCiAgICAiaGVhZGVyVGV4dENvbG9yIjogInRleHQtc2xhdGUtNTAiLAogICAgImhlYWRlckdyYWRpZW50RGlyZWN0aW9uIjogImJnLWdyYWRpZW50LXRvLWIiLAogICAgImhlYWRlckdyYWRpZW50RnJvbUNvbG9yIjogImZyb20tcmVkLTk1MCIsCiAgICAiaGVhZGVyR3JhZGllbnRUb0NvbG9yIjogInRvLXN0b25lLTk1MCIsCiAgICAiYXZhdGFyU2l6ZSI6ICJ3LTEwIGgtMTAiLAogICAgImxhdW5jaGVyQm9yZGVyIjogNCwKICAgICJjaGF0QmFja2dyb3VuZCI6ICJiZy1zbGF0ZS01MCIsCiAgICAiYnViYmxlVXNlckJhY2tncm91bmQiOiAiYmctc2xhdGUtODAwIiwKICAgICJidWJibGVVc2VyVGV4dENvbG9yIjogInRleHQtc2xhdGUtNTAiLAogICAgImJ1YmJsZUJvdEJhY2tncm91bmQiOiAiYmctc2xhdGUtNTAiLAogICAgImJ1YmJsZUJvdFRleHRDb2xvciI6ICJ0ZXh0LXNsYXRlLTkwMCIsCiAgICAiYnViYmxlUmFkaXVzIjogInJvdW5kZWQtMnhsIiwKICAgICJidWJibGVQYWRkaW5nWCI6ICJweC00IiwKICAgICJidWJibGVQYWRkaW5nWSI6ICJweS0yIiwKICAgICJoZWFkZXJHcmFkaWVudCI6ICJiZy1ncmFkaWVudC10by1iIGZyb20tcmVkLTk1MCB0by1zdG9uZS05NTAiCiAgfSwKICAiYWxsb3dGdWxsU2NyZWVuIjogdHJ1ZSwKICAic2hvd0F0dGFjaG1lbnRCdXR0b24iOiB0cnVlLAogICJzaG93TWljQnV0dG9uIjogZmFsc2UsCiAgInNob3dTZWFyY2hCdXR0b24iOiBmYWxzZSwKICAiaGludFRleHQiOiAiQXNrIG1lIiwKICAicHJpdmFjeVBvbGljeVVybCI6ICJodHRwczovL3d3dy56aWp1cy5jb20vcHJpdmFjeS1wb2xpY3kiLAogICJ3ZWJzb2NrZXRVcmwiOiAid3NzOi8vc3R1ZGlvLnppanVzLmNvbS93cy96aWp1cy01MzUxIiwKICAibGFuZ3VhZ2VzIjogWwogICAgewogICAgICAiY29kZSI6ICJFTl9VUyIsCiAgICAgICJuYW1lIjogIkVuZ2xpc2giCiAgICB9LAogICAgewogICAgICAiY29kZSI6ICJISV9JTiIsCiAgICAgICJuYW1lIjogIkhpbmRpIgogICAgfSwKICAgIHsKICAgICAgImNvZGUiOiAiRlJfQ0EiLAogICAgICAibmFtZSI6ICJGcmVuY2giCiAgICB9LAogICAgewogICAgICAiY29kZSI6ICJFU19FUyIsCiAgICAgICJuYW1lIjogIlNwYW5pc2giCiAgICB9LAogICAgewogICAgICAiY29kZSI6ICJBUiIsCiAgICAgICJuYW1lIjogIkFyYWJpYyIKICAgIH0KICBdLAogICJjaGF0Ym90SWNvbiI6ICJodHRwczovL3N0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vemlqdXNzdGF0aWMvaW1hZ2VzL1ppanVzSWNvblNxLnBuZyIsCiAgInRpdGxlSWNvbiI6ICJodHRwczovL3N0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vemlqdXNzdGF0aWMvaW1hZ2VzL1ppanVzSWNvblNxLnBuZyIsCiAgInN1YnNjcmlwdGlvblR5cGUiOiAiaWduaXRlIiwKICAic3BlYWtlck1vZGUiOiB0cnVlLAogICJ2b2ljZUlucHV0IjogdHJ1ZQp9" >
    < /script> <
    /body> <
    /html>